#!/usr/bin/env bash
# Render this repo's Go wire types to TypeScript with tygo (config: tygo.yaml).
# The Go structs are the source of truth. Each output file named in tygo.yaml
# gets a header recording the commit it was generated from.
set -euo pipefail
cd "$(dirname "$0")"
export PATH="$HOME/.local/share/mise/shims:$(go env GOBIN 2>/dev/null || echo "$HOME/go/bin"):$PATH"

MODULE=$(awk '/^module /{print $2}' go.mod)
COMMIT=$(git rev-parse HEAD)
SHORT=$(git rev-parse --short HEAD)
DIRTY=""
git diff --quiet HEAD -- . || DIRTY="-dirty"

echo "==> Generating TypeScript types for ${MODULE} (commit ${SHORT}${DIRTY})..."
tygo generate

for OUTFILE in $(awk '/output_path:/{gsub(/"/,"",$2); print $2}' tygo.yaml); do
  TMPFILE=$(mktemp)
  cat > "$TMPFILE" <<HEADER
// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from ${MODULE} @ ${COMMIT}${DIRTY}
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

HEADER
  cat "$OUTFILE" >> "$TMPFILE"
  mv "$TMPFILE" "$OUTFILE"
  echo "    wrote $OUTFILE ($(wc -l < "$OUTFILE") lines, commit ${SHORT}${DIRTY})"
done
