// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/work-graph-store @ 67ba8a68582b80f05044d468d01dcb9f22c3252e
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: commit.go

/**
 * CommitAnswer is GET /commits/{mention...}: the commit, and the repo it is in as
 * repo-store has it.
 */
export interface CommitAnswer {
  repo: Repo;
  commit: Commit;
}

//////////
// source: graph.go

/**
 * Commit is one commit as git has it, with the session that made it when this
 * store saw that happen.
 */
export interface Commit {
  sha: string;
  parents: string[];
  committed_at: number /* int64 */;
  author_name: string;
  subject: string;
  /**
   * MadeBy is nil when no session on this host is known to have made it.
   */
  made_by?: CommitAuthorship;
  /**
   * OnRemoteBranch says a remote-tracking branch contains the commit, so it
   * was pushed (as of the clone's last fetch) and a link to it on the
   * repo's host will not 404.
   */
  on_remote_branch: boolean;
}
/**
 * BranchSession is one session's part in a branch's history.
 */
export interface BranchSession {
  session_id: string;
  /**
   * RefUpdates counts the times the session moved the branch.
   */
  ref_updates: number /* int */;
  /**
   * Checkouts counts the times the session checked the branch out.
   */
  checkouts: number /* int */;
  git_subcommands: string[];
  first_at_unix_nano: number /* int64 */;
  last_at_unix_nano: number /* int64 */;
}
/**
 * Branch is a local or remote-tracking branch.
 */
export interface Branch {
  /**
   * Ref is the full name ("refs/heads/main", "refs/remotes/origin/main").
   */
  ref: string;
  name: string;
  is_remote: boolean;
  head_sha: string;
  committed_at: number /* int64 */;
  /**
   * MergedIntoDefault says the default branch contains the head.
   */
  merged_into_default: boolean;
  /**
   * WorktreePath is the worktree that has the branch checked out, or "".
   */
  worktree_path: string;
  sessions: BranchSession[];
}
/**
 * Graph is one repo's commit graph.
 */
export interface Graph {
  repo: Repo;
  /**
   * DefaultBranch is resolved as deploy-gate resolves it: the branch
   * origin/HEAD names, else main, else master; "" when none exists.
   */
  default_branch: string;
  commits: Commit[];
  branches: Branch[];
  /**
   * Truncated says there are older commits than those listed.
   */
  truncated: boolean;
}

//////////
// source: ingest.go

/**
 * Ingester moves the hook's spool into the store.
 * The hook appends; the ingester renames the spool aside, waits for any hook
 * that opened it before the rename to finish its one write, reads the whole
 * file into one transaction, and deletes it. A spool left aside by a crash is
 * read first on the next pass, so nothing is read twice or lost.
 */
export interface Ingester {
  Store?: Store;
  SpoolPath: string;
  RepoStore?: RepoStoreClient;
  /**
   * Interval is the pause between passes.
   */
  Interval: any /* time.Duration */;
  /**
   * SettleDelay is how long a renamed spool sits before it is read.
   */
  SettleDelay: any /* time.Duration */;
}
/**
 * Repo is the part of a repo-store repo this service reads.
 */
export interface Repo {
  id: number /* int64 */;
  name: string;
  path: string;
  /**
   * GitHubURL is repo-store's github_url: the repo's page on GitHub, or ""
   * when its remote is not there.
   */
  github_url?: string;
}
/**
 * RepoStoreClient asks repo-store about repos.
 */
export interface RepoStoreClient {
  BaseURL: string;
  HTTP?: any /* http.Client */;
}

//////////
// source: server.go

/**
 * Handlers serves the HTTP routes CONTRACT.md lists.
 */
export interface Handlers {
  Store?: Store;
  RepoStore?: RepoStoreClient;
}
/**
 * RepoActivity is one repo's local branches that sessions touched recently.
 */
export interface RepoActivity {
  repo: Repo;
  default_branch: string;
  branches: Branch[];
  /**
   * DeletedBranches are refs sessions touched in the window that no longer
   * exist, usually because they were merged and cleaned up.
   */
  deleted_branches: string[];
}

//////////
// source: store.go

/**
 * RefUpdate is a stored ref update.
 */
export interface RefUpdate {
  id: number /* int64 */;
  recorded_at_unix_nano: number /* int64 */;
  session_id: string;
  hook: string;
  git_subcommand: string;
  /**
   * RepoStoreID is 0 when repo-store has no repo at RepositoryPath.
   */
  repo_store_id: number /* int64 */;
  repository_path: string;
  worktree_path: string;
  ref: string;
  old_sha: string;
  new_sha: string;
}
/**
 * Store is the SQLite database of ref updates.
 */
export interface Store {
}
/**
 * RefUpdateFilter narrows ListRefUpdates. A zero field does not filter.
 */
export interface RefUpdateFilter {
  RepoStoreID: number /* int64 */;
  SessionID: string;
  Ref: string;
  SinceUnixNano: number /* int64 */;
  Limit: number /* int */;
}
/**
 * CommitAuthorship is which session made a commit.
 */
export interface CommitAuthorship {
  sha: string;
  session_id: string;
  git_subcommand: string;
  recorded_at_unix_nano: number /* int64 */;
}
